### ISSUE TITLE
I would like to create a server 

### ISSUE THREAD

**Issue by HenryKUNliao** [nekomaster1000/Resurvival-Housekeeping#14]
As the title says. I would like to create a serves with this modpack to play with friends.
I downloaded the client-side modpack via de curseforge app but there is no "server file/zip" so i could host my own server and I don´t really know what mods are essential in this scenario. 
My intention is to leave it open so some of my friends can play as they have time and not only when i´m available
Thanks in advance for any comments on this.
And sorry for my bad english since it´s clearly not my main language

**Comment by nekomaster1000** [comment]
Hi! The modpack is very big, so I would advise paying for a dedicated server to run it. You can get 25% off a Bisect server with the code 'Infernalstudios': https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fbisecthosting.com%252finfernalstudios
