### ISSUE TITLE
General feedback and tweak suggestions

### ISSUE THREAD

**Issue by CrystalZink** [nekomaster1000/Resurvival-Housekeeping#2]
Not all of these things are completely necessary, but its what I've got from the time iI've played.
There might be some typos cuz I woke up like 25 minutes ago and I'm on a bit of a rush,
These were thoughts from v1.3.0, I haven't seen the v1.4.0 changelog yet so lul.
This post is a combination of bugs and recommendations (altho more of the latter cuz I haven't encountered many bugs):

Issues:
- Tetra swords don't work with inventorio's sword slot
- Shaders cause frequent crashes (ie. Die with shaders, use a tetra bow with shaders ect.)

General feedback:
- Skeleton detection range should be a bit smaller, its very easy for multiple skeletons to be shooting you from multiple angles and it becomes annoying
- Skeletons that shoot extremely fast could have less accuracy, maybe it could be random as to which ones are accurate and which ones aren't
- Hurting any animal that's in a group of the same animals should make the entire herd run away from you (maybe some animals could defend themselves?)
- Alex Mob grappling squok recipe should have a grappling hook instead of a crossbow (maybe a texture change to accomodate that?)
- More baby mobs (baby skeletons, wither skeletons ect.) because why not make it more of a pain than it is?
- Enderian origin's ender pearl cooldown should be much longer (you can cross large distances with it easily, 10-20 second cooldown maybe?)
- Terralith structure loot tables either heavily edited or flat out removed, plus some biomes (ie yellowstone biome) should be removed cuz you can easily progress in some mods (tetra) very quickly with it, a terralith structure has fuckin end rods, VERY GOOD FOR TETRA TOOLS BTW
- Feline origin could be nerfed a bit, maybe some creepers could randomly spawn that aren't afraid of the origin (the player not other cats), it would still make them a threat but not as big of one

Texture edits (not necessary at all):
- Endronium (Plus the end) textures should be changed to match the rest of the tools from the pack (also should be changed in general cuz rn its kinda mid)
- Copper Overhaul chestplate textures changed to match the rest of the pack

Misc. Recommendations:
- Nock Enough Arrows Mod
Adds a ton of different arrow types and even a quiver, even adds functionality to the fletching table!
- Allurement: disabling the protection enchant - could literally encourage the usage of other prot enchants, cuz prot 4 + heartfelt 2 on all armor pieces is just cracked tbh
- Recipes:
Being able to upgrade stone->diamond tools the same way you upgrade wood to stone, tool in one slot and the amount of materials needed to upgrade in the other slots

**Comment by nekomaster1000** [comment]
Very good feedback! Thanks for taking the time to write this :D 

The Grappling Squok recipe was indeed changed in 1.4, thanks for that idea!
Also worth noting that Supplementaries adds a Quiver in its newest versions ;D

I'll try and address more of these in future updates, too :] 👍
I appreciate that you like my custom stone tools upgrading recipe!

**Comment by SwanX1** [comment]
One of the issues is related to Lizard-Of-Oz/Inventorio#95

**Comment by nekomaster1000** [comment]
> [Lizard-Of-Oz](https://github.com/Lizard-Of-Oz) added the [compatibility issues](https://github.com/Lizard-Of-Oz/Inventorio/labels/compatibility%20issues) This issue is caused by interaction with another modlabel [on 9 Jan](https://github.com/Lizard-Of-Oz/Inventorio/issues/95#event-5861972101)

@CrystalZink I don't think the Tetraventorio bug is getting fixed anytime soon buddy HAHA
