### ISSUE TITLE
add vanillatweaks resource pack

### ISSUE THREAD

**Issue by SwanX1** [nekomaster1000/Resurvival-Housekeeping#4]
https://vanillatweaks.net/share#ueFg8c

<details>
<summary>
Enabled tweaks:
</summary>

- Aesthetic
  - DarkOakSaturation
  - SmootherWarpedPlanks
  - AshlessCampfires
  - UniqueDyes
  - StemToLog
  - BetterParticles
  - RedIronGolemFlowers
  - SofterWool
  - DifferentStems
- Terrain
  - SmootherStones
  - CircleLogTops
  - SmootherOakLog
  - DarkerDarkOakLeaves
- Utility
  - NoteblockBanners
  - VisualHoney
  - UnlitRedstoneOre
  - Age25Kelp
  - VisualWaxedCopperItems
  - VisualInfestedStoneItems
- Unobtrusive
  - TransparentPumpkin
  - UnobtrusiveScaffolding
  - UnobtrusiveParticles
- Hud
  - WitherHearts
- Fixes
  - HopperBottomFix
  - BlazeFix
  - PixelConsistentXPOrbs
  - CocoaBeansTopFix
  - CactusBottomFix
  - ConsistentBucketFix
  - DripleafFixSmall
  - DripleafFixBig
  - RedstoneWireFix
</details>

**Comment by nekomaster1000** [comment]
Done, mostly!
