### ISSUE TITLE
add End's Phantasm mod

### ISSUE THREAD

**Issue by Lyof429** [nekomaster1000/Resurvival-Housekeeping#5]
I suggest to add End's Phantasm to the pack (https://www.curseforge.com/minecraft/mc-mods/phantasm)
I think it works well at expanding the End in a vanilla friendly way, and adds some unique stuff as an incentive to explore it further than simply getting an Elytra
If two end mods is too many, I think Plus the End is the one to delete, as its features are basically all recolors of 1.16 textures and don't bring new gameplay elements. Else, know they look nice together:
![image](https://user-images.githubusercontent.com/90898724/191967115-b4f6ef73-0d87-47b0-93b9-c684a7a7208d.png)

As I'm both a kinda active member on IS and its developper, feedback and questions could also be quickly replied

**Comment by nekomaster1000** [comment]
Will be done in version 2.0 of the pack!

**Comment by nekomaster1000** [comment]
Oh damn I did this a while ago LOL
