### ISSUE TITLE
Pickarangs can easily be deleted from your inventory when attacking

### ISSUE THREAD

**Issue by CrystalZink** [nekomaster1000/Resurvival-Housekeeping#7]
v1.6.0
Steps on how to reproduce:
- 1) Put any kind of sword in your sword inventorio slot and use a pickarang on a mob
- 2) inventorio is gonna attack the mob with said sword, its gonna have the sword being thrown instead of the pickarang which is kinda funny tbh
- 3) ur gonna lose ur pickarang and ur sword is gonna be where the pickarang was

mfw i lost 2 pickarangs due to this and one was rlly good

**Comment by nekomaster1000** [comment]
Inventorio is no longer in the pack 👍
