### ISSUE TITLE
Infinity Tetra bows crash the game

### ISSUE THREAD

**Issue by CrystalZink** [nekomaster1000/Resurvival-Housekeeping#8]
Steps to reproduce:
1. get a tetra bow
2. put infinity on it
3. shoot it
4. instant crash

also heres a log
https://mclo.gs/Fxe9MLR

**Comment by SwanX1** [comment]
Hi there! It seems this may be a compatibility issue with Inventorio, please report this on [their issue tracker](https://github.com/Lizard-Of-Oz/Inventorio/issues/new/choose), and mention it as an incompatibility with Tetra.
Relevant line of code: [PlayerInventoryInjects.kt line 34](https://github.com/Lizard-Of-Oz/Inventorio/blob/1.18.2/common/src/main/kotlin/me/lizardofoz/inventorio/player/inventory/PlayerInventoryInjects.kt#L37)

**Comment by nekomaster1000** [comment]
Tetra is no longer in the pack :]
