### ISSUE TITLE
Add Combat Roll and Excavated Variants

### ISSUE THREAD

**Issue by CrystalZink** [nekomaster1000/Resurvival-Housekeeping#9]
https://www.curseforge.com/minecraft/mc-mods/combat-roll
Combat Roll basically lets you do a cool roll move, adds 2 new enchantments, would be extremely useful for combat
(basically elenai dodge for 1.18.2-1.19.2 lol)

https://www.curseforge.com/minecraft/mc-mods/excavated-variants
Excavated Variants adds more variant ore blocks to make caves feel more natural
Bonus is that it has support for a lot of mods, including MM!

**Comment by nekomaster1000** [comment]
Combat Roll is so based, thanks for the suggestion!
